### ISSUE TITLE
Add gazebo support 

### ISSUE THREAD

**Issue by jediofgever** [ros-industrial/fanuc#281] opened 2019-10-11 14:51 UTC
Hello, 

I saw that previously there was an issue regarding to the development of gazebo support and I also come to see there have been some respectively long waiting PRs but not merged into any branched.
I would like to know;
* is there any plans/willingness to include gazebo support  

I am willing to collaborate and contribute to add support of gazebo.

Thank you for your time.

**Comment by gavanderhoorn** [comment] 2019-10-11 16:16
Moved this to `ros-industrial/fanuc` and also closing as a duplicate of #145.

@jediofgever: let's continue the discussion there.

**Closed as completed by gavanderhoorn** 2019-10-11 16:16 UTC
