### ISSUE TITLE
Trying to compile X_moveit_plugins on melodic

### ISSUE THREAD

**Issue by joao-pm-santos96** [ros-industrial/fanuc#258] opened 2019-03-09 17:19 UTC
When compiling on ubutnu 18.04, ROS Melodic, it can't find the function 'getTipFrame()' that it defined on 'kinematics_base.h' that I verified to have in my system. Is there come way to solve it? 

The package includes moveit_core but the path to 'kinematics_base.h': is /opt/ros/melodic/include/moveit/kinematics_base

![Screenshot from 2019-03-09 17-18-39](https://user-images.githubusercontent.com/47630528/54074840-79a31c00-428f-11e9-9c09-7045c5beb03d.png)

@miguelriemoliveira

**Comment by gavanderhoorn** [comment] 2019-03-09 17:21
This is a duplicate of #241.

Not that it isn't a problem, but let's keep the nr of duplicates to a minimum.

**Closed as completed by gavanderhoorn** 2019-03-09 17:21 UTC

**Comment by miguelriemoliveira** [comment] 2019-03-09 17:22
Hi @joao-pm-santos96 

I will try to compile on my laptop. 

Can you create a section in this repository's readme file in which you explain how to install / build this package (whatever steps you have done until now)?  

For now the issue is assigned to you ... Then I will try to compile from my side.

**Comment by miguelriemoliveira** [comment] 2019-03-09 17:23
@joao-pm-santos96 , please add me as a collaborator to your repository ...

**Comment by miguelriemoliveira** [comment] 2019-03-09 17:23
and I think you had an answer already ... great !

**Comment by gavanderhoorn** [comment] 2019-03-09 17:24
I'm slightly confused by the many comments here ..

**Comment by miguelriemoliveira** [comment] 2019-03-09 17:27
Sorry @gavanderhoorn , my fault. I thought I was writting on @joao-pm-santos96 (my students) repository. 
I did not realize it was another repository. I will try to remove my comments.

**Comment by gavanderhoorn** [comment] 2019-03-09 17:28
@joao-pm-santos96: please don't post screenshots of terminals. It's all text, so copy-paste the console text into your comments.

**Comment by joao-pm-santos96** [comment] 2019-03-09 17:33
@gavanderhoorn sorry, I'm new to github but I'm very thankful for your quick answer it solved the problem!
@miguelriemoliveira Yeah I didn't add it to my repository, nevertheless I'll add you as contributor, also thank you for the quick reply.
