### ISSUE TITLE
Fanuc M710iC-50 kinematics

### ISSUE THREAD

**Issue by christianlandgraf** [ros-industrial/fanuc#290] opened 2020-06-04 13:30 UTC
Hello,

while working with the Fanuc M710ic50 and fanuc_m710ic_support package, I noticed that the robot behaviour differs from the real robot and the layout in Visual Components. It seems, as if there is a mistake in the urdf of this package.

For example, if I set the following joint states as can be seen in the picture, the robot is in the displayed position:
![Selection_056](https://user-images.githubusercontent.com/28567122/83762191-8e7b8480-a677-11ea-9839-f5179a5c7bde.png)

But if I set the same joint states in Visual Components, it looks like:
![2](https://user-images.githubusercontent.com/28567122/83762247-a05d2780-a677-11ea-9f2a-8d2ec004fe7f.PNG)

Even without the exact solution one cane see, that this is not correct.

Since the actual robot behaves as Visual Component expects, I suppose there is a bug in the ROS package. I will have a look and try to fix it but maybe there is someone else out there, who is more experienced with URDF and can immediately fix the bug. 

I can also give the robot parameters which are set in Visual Components, if desired. Unfortunateley, I do not have access to the real robot at the moment.

Thanks a lot
Christian

**Comment by gavanderhoorn** [comment] 2020-06-04 13:37
I suspect Visual Components is showing you the joint angles as the teach pendant would, which includes the so called "joint 2 - joint 3 coupling".

In ROS, we do not do this, and give you the plain joint angles.

Please see ros-industrial/fanuc_experimental#17 for a similar case.

**Comment by gavanderhoorn** [comment] 2020-06-04 13:39
And see also [J3 on TP and joint_3 in ROS do not match](http://wiki.ros.org/action/show/fanuc_driver/Troubleshooting#J3_on_TP_and_joint_3_in_ROS_do_not_match) in the Troubleshooting guide.

**Comment by gavanderhoorn** [comment] 2020-06-04 13:41
I'm going to assume the linked issue and the FAQ entry explain the cause of what you're seeing.

Assuming that's true, I'm going to close this issue, as it's not really a problem with the robot support package -- or at least not something we can fix: "joint coupling" is not a concept in ROS.

If it turns out there is actually something wrong, we can re-open.

In the meantime, feel free to keep commenting of course.

**Closed as completed by gavanderhoorn** 2020-06-04 13:41 UTC
Labels: status:works-for-me

**Comment by christianlandgraf** [comment] 2020-06-04 13:56
Thanks a lot for the quick answer! I wasn't aware of that, it worked with the Troubleshooting guide.
